<?php
   $texto = "Gilberto Giansante e Vinicius Spaggiari 
   01/12/2009

   Derrotas, fracassos, demissões. Como sempre, o advento das crises econômicas leva o debate público às regiões sombrias do capitalismo, nas quais se materializam os fatos colocados além da previsibilidade hodierna dos agentes econômicos. Por isso, nesse último ano, em diversas áreas do conhecimento, foram questionadas as soluções institucionais para a gestão adequada de tais eventos.

   Logo, na disciplina jurídica a eficiência do arcabouço institucional concursal (recuperacional e falimentar) tem sido a bola da vez. Aqui é abordada principalmente jurisprudência da Lei nº 11.101, de 2005, na constância de maré tão adversa. Frisando-se, de forma central, o papel do princípio da preservação da empresa em tal sistemática.

   Inicialmente, vale o recurso a Trajano de Miranda Valverde, que definia o instituto da falência como um complexo de regras jurídicas técnicas ou construtivas, que definem e regulam uma situação especial, de ordem econômica, a falência (Comentários à Lei de Falências, vol. 1, 2ª ed., Revista Forense, Rio de Janeiro, 1955, p. 20). O autor clássico se referiu, à época, somente à gestão institucional do crédito diante do colapso empresarial (limite claro da legislação falimentar de seu tempo). Atualmente, entretanto, a Lei de Recuperação Judicial procura, por meio do complexo de regras jurídicas técnicas ou construtivas, ir além.

   Direciona a preservação da empresa, em sua consistência econômica, e com a estrutura do bem-estar social a ela conectada. Determinação que, nas decisões judiciais, chega mesmo a derrogar (contra ou a favor a pontos específicos da legislação) princípios de grande peso na ordem legal brasileira - por exemplo, o de que o risco da atividade econômica pertence ao empregador, ou mesmo o da supremacia do crédito tributário etc. Dessa forma, (a) realizar a gestão limite do crédito no comércio, (b) proteger os interesses com menor poder fático (de negociação, subsistência econômica, obtenção e gestão de informação etc.), (c) estabilizar as expectativas gerais sobre o colapso empresarial, (d) controlar os riscos inerentes ao processo judicial concursal, são algumas das funções inerentes à Lei de Recuperação Judicial que vêm sendo condicionadas por uma lógica jurisprudencial sistêmica constituída em torno do princípio da preservação da empresa.

   Note-se, para o Supremo Tribunal Federal, na Adin 3934-2, do ponto de vista teleológico, salta à vista que o referido diploma legal buscou, antes de tudo, garantir a sobrevivência das empresas em dificuldades - não raras vezes derivadas das vicissitudes por que passa a economia globalizada -, autorizando a alienação de seus ativos, tendo em conta, sobretudo, a função social que tais complexos patrimoniais exercem, a teor do disposto no artigo 170, III, da Lei Maior.

   Com a decisão, confirmou-se a constitucionalidade dos artigos 60, parágrafo único e 141, § 1º, da lei. Portanto, na aquisição de ativos na recuperação judicial ou na falência, o adquirente não compra riscos sucessórios. Somente os ativos, que são vendidos com maior valor. Os créditos tributários e os trabalhistas permanecem com a original proprietária do bem vendido. No entanto, por determinação da mesma lógica, a recuperanda se capitaliza mais rápido. Tem menor dificuldade para girar sua atividade e cumprir o plano de recuperação. Mais impostos para o Estado, menos demissões de trabalhadores. Em ambos os casos, falência ou recuperação judicial, os credores tendem a receber mais rapidamente valores maiores.

   Ocorre que decisões guiadas por lógica convergente se direcionam também contra o texto da lei: Não se mostra plausível a retomada das execuções individuais após o mero decurso do prazo legal de 180 dias - limite legalmente explícito no artigo 6º, § 4º , Lei de Recuperação. Este Conflito de Competência nº 68.173 do STJ considera que, no que tange à matéria,  permitir (antes do prazo legal de 180 dias) que cada um defenda o seu crédito implica em colocar abaixo o princípio nuclear da recuperação, que é o do soerguimento da empresa, a par de colocar em risco o princípio da par conditio creditorum  . Ou seja, Se a incompatibilidade tem lugar entre uma disposição principal e uma disposição acessória, então leva à ineficácia da última, deixando firme a disposição fundamental (FERRARA, Francesco, Ensaio sobre a Teoria da Interpretação das Leis, trad. Manuel Domingues de Andrade, 4ª ed., Editor Sucessor, Coimbra, 1987, p. 151/152).

   Do mesmo modo, quando outras tensões entre normas aparecem nos julgamentos da Lei de Recuperações, mostra-se patente a necessidade de escolher entre elas. Por exemplo, por meio do art. § 4º, art. 6º, LRE, o TJSP, contra a exclusão legalmente explícita no artigo 49, § 1º, LRE, decidiu, na Apelação nº 7.166.479-6 e nos relativos Embargos Infringentes nº 7.166.479-6/02, que: os sócios da empresa que obteve a recuperação judicial, com a homologação do plano para pagamento futuro de seus credores, devedores solidários que são, seja como avalistas, ou qualquer outra espécie de garante, são atingidos pelo efeito, repita-se, do benefício da recuperação judicial. Pela decisão vincula-se à atividade econômica os créditos a ela relativos. Os garantes, majoritariamente os sócios nas micro e pequenas empresas, passam a contar com o prazo de blindagem do § 4º, artigo 6º, da Lei de Recuperações.

   Tensões entre jurisprudência e texto legal que, embora não sejam novidades, têm gerado constantes alertas sobre a corrosão da segurança jurídica em tais operações interpretativas - frise-se: também a jurisprudência da antiga Lei de Falências, acabou se sobrepondo a diversas normas textualmente explícitas em prol da construção de uma ordem legal socialmente adequada. Ocorre que de tal dinâmica (como sói ocorrer quando se utiliza de um princípio jurídico para operação de tal viés, e.g. PERELMAN, Chaïm, Trad. Vergínia K. Pupi, Lógica Jurídica, Nova Retórica, Martins Fontes, São Paulo, 2000, p. 88/104) derivam a adaptação e a evolução da legislação à ordem legal sistêmica, e, sobretudo, à sociedade onde se insere.

   No caso, por meio da crescente normatividade conferida ao princípio da preservação da empresa para reger a aplicação da Lei de Recuperação, reforça-se a proteção legal do arcabouço de bem-estar social concretamente constituído e gerenciado pela atividade empresarial. Por isso, bons os ventos que sopram da jurisprudência nessa direção. Que na evolução futura da Lei, eles sigam mais e mais esse sentido.

   Gilberto Giansante e Vinicius Spaggiari são advogados do Giansante Advogados

   Este artigo reflete as opiniões do autor, e não do jornal Valor Econômico. O jornal não se responsabiliza e nem pode ser responsabilizado pelas informações acima ou por prejuízos de qualquer natureza em decorrência do uso dessas informações;";
   
   echo strlen($texto);
?>
